### ISSUE TITLE
Please change

### ISSUE THREAD

**Issue by p1d1d1** [MediaComem/eCH-0056-revision#1]
In https://github.com/MediaComem/eCH-0056-revision/tree/main/01_kick-off_meeting#discussion:

<html>
<body>

Pasquale Di Donnato | - Delivering INTERLIS-GML is in principle impossible
-- | --

</body>
</html>

It's not exactly what I said. Please change to:

<html>
<body>

Pasquale Di Donato | - Delivering INTERLIS-GML via WFS is a very complex task and it's not by every GIS Server.
-- | --

</body>
</html>

**Comment by p1d1d1** [comment]
See pull request

**Comment by maxcollombin** [comment]
Your request as been merged. 
Thanks for your feedback and sorry for the missunderstanding @p1d1d1 .
